.PHONY: all clean showdir tog

all: showdir tog

showdir:
	$(MAKE) -C resouces/showdir

showdir_clean:
	$(MAKE) -C resouces/showdir clean

tog:
	$(MAKE) -C resouces/tog

tog_clean:
	$(MAKE) -C resouces/tog clean

clean:
	$(MAKE) -C resouces/showdir clean
	$(MAKE) -C resouces/tog clean